#Requires -Version 5.1
<#
.SYNOPSIS
  Erzeugt eine sync-server/.env mit frischen, kryptographisch zufaelligen Secrets.
.DESCRIPTION
  Wird von build.bat aufgerufen. Schreibt NIE die Dev-.env des Entwicklers
  ins Bundle, damit JWT_*/SESSION_SECRET pro Build einzigartig sind.
#>
param(
  [Parameter(Mandatory = $true)]
  [string]$OutPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function New-HexSecret {
  param([int]$Bytes = 48)
  $buf = New-Object byte[] $Bytes
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($buf)
  } finally {
    $rng.Dispose()
  }
  -join ($buf | ForEach-Object { '{0:x2}' -f $_ })
}

$lines = @(
  '# Auto-generated by build.bat - do NOT commit this file.',
  '# Each build regenerates these secrets; if you want stable secrets across',
  '# builds, replace this file by hand AFTER the build (or set them in your host env).',
  'PORT=3000',
  'DB_PATH=data/teamlink.db',
  'NODE_ENV=production',
  ('SESSION_SECRET={0}' -f (New-HexSecret)),
  ('JWT_ACCESS_SECRET={0}' -f (New-HexSecret)),
  ('JWT_REFRESH_SECRET={0}' -f (New-HexSecret)),
  '# Local origins for the Flutter client that runs on the same machine as the host server.',
  '# Cloudflare tunnel origins (*.trycloudflare.com) are accepted dynamically in code,',
  '# they do NOT need to be listed here.',
  'ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000'
)

$dir = Split-Path -Parent $OutPath
if (-not (Test-Path $dir)) {
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

# UTF-8 ohne BOM, damit dotenv den Inhalt korrekt liest.
[System.IO.File]::WriteAllLines($OutPath, $lines, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Bundle .env geschrieben: $OutPath"
